Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 2
    vb.name = "Vagrant"
  end
  config.vm.hostname = "user"
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install openjdk-7-jdk scala
    sudo apt-get -y autoremove
  SHELL
end

